-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 18:47:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema od_suap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema od_suap
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `od_suap`;
CREATE SCHEMA IF NOT EXISTS `od_suap` DEFAULT CHARACTER SET utf8 ;
USE `od_suap` ;

-- -----------------------------------------------------
-- Table `od_suap`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `od_suap`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `matricula` VARCHAR(45) NULL,
  `curso` VARCHAR(100) NULL,
  `ingresso` VARCHAR(45) NULL,
  `periodo` VARCHAR(45) NULL,
  `matriz` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `situacao_sistemica` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
